spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# Force data.sql to run on external (PostgreSQL) database
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true